### ISSUE TITLE
Install with Meteor 1.11.1 failed

### ISSUE THREAD

**Issue by juliensl** [monti-apm/meteor-profiler#2]
Hi everybody ! 

I'm looking to use this app which looks like very easy and powerfull :) 
I tried to install this package to have access to the CPU profiler, but I got a similar issue than here : #1 

```
=> Errors while adding packages:                                                  
                                              
While loading montiapm:agent-binary-deps@2.0.0...:
error: Command failed:
/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --update-binary
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError
(/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F
(/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E
(/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at
/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at
/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at
/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
gyp ERR! System Linux 5.8.0-36-generic
gyp ERR! command
"/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/tmp/mt-1i5tsxp.8n8ok/npm/node_modules/.temp-1n6oexk.bdkq/node_modules/v8-profiler-next
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-next@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler-next@1.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output
above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/julien/.npm/_logs/2021-01-12T13_55_42_213Z-debug.log
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError
(/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F
(/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E
(/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at
/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at
/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at
/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
gyp ERR! System Linux 5.8.0-36-generic
gyp ERR! command
"/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/julien/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/tmp/mt-1i5tsxp.8n8ok/npm/node_modules/.temp-1n6oexk.bdkq/node_modules/v8-profiler-next
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-next@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler-next@1.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output
above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/julien/.npm/_logs/2021-01-12T13_55_42_213Z-debug.log
```

I'm using Meteor 1.11.1

Thank your for your work ! :)

**Comment by zodern** [comment]
It looks like you are missing the dependencies required by node-gyp: https://github.com/nodejs/node-gyp#on-unix
